// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Ninth House Studios LLC

import '../ephe/download_spec.dart';

/// A higher-coverage city-atlas tier offered as an optional download.
///
/// The app bundles GeoNames cities5000 (~70k places) on every platform. These
/// tiers trade download size for coverage and are native-only — the web build
/// has no managed filesystem and always uses the bundle.
///
/// The tiers form a strict superset chain (cities500 ⊃ cities1000 ⊃
/// cities5000), so an installed tier WHOLESALE-REPLACES the bundle — it is
/// never merged. [atlasReleases] is therefore ordered highest-coverage first
/// so the loader picks the biggest installed tier in one pass.
///
/// Data © GeoNames (CC BY 4.0). Files are gzipped TSVs in the same column
/// layout as the bundled `cities.tsv` (name, admin1, country, lat, lon,
/// population, tz), generated by `tool/gen_atlas.dart`.
class AtlasRelease {
  const AtlasRelease({
    required this.filename,
    required this.displayName,
    required this.approxCities,
    required this.url,
    required this.sizeBytes,
    required this.md5,
  });

  /// On-disk name under `<ephe-root>/atlas/`. The gzip extension is kept; the
  /// loader decompresses in memory.
  final String filename;

  /// Label shown in the manager row (e.g. "Cities ≥ 500 population").
  final String displayName;

  /// Approximate row count, for the UI subtitle.
  final int approxCities;

  final String url;

  /// Size of the gzipped download, used for the progress bar and the
  /// (never-tripped, these are small) large-download confirmation.
  final int sizeBytes;

  /// md5 of the gzipped file. Pinned so a truncated or error-page download is
  /// rejected — the atlas never relies on the ephe payload sniff.
  final String md5;

  /// Lower this tier onto the downloader's transfer unit. Lands in the
  /// `atlas/` subdir, which the ephemeris scanner deliberately does not walk.
  DownloadSpec toDownloadSpec() => DownloadSpec(
    url: url,
    filename: filename,
    subdir: atlasSubdir,
    sizeBytes: sizeBytes,
    md5: md5,
  );
}

/// Subdirectory (relative to the managed ephe root) that downloaded atlas
/// tiers live in. Kept out of the ephemeris scanner's walk so a gazetteer is
/// never mistaken for — or handed to — the Swiss Ephemeris engine.
const String atlasSubdir = 'atlas';

const String _atlasBaseUrl =
    'https://ninthhouse.studio/ephemeris-dashboard/atlas';

/// Optional atlas tiers, ordered HIGHEST coverage first (see [AtlasRelease]).
const List<AtlasRelease> atlasReleases = [
  AtlasRelease(
    filename: 'cities500.tsv.gz',
    displayName: 'Cities ≥ 500 population',
    approxCities: 235747,
    url: '$_atlasBaseUrl/cities500.tsv.gz',
    sizeBytes: 5706722,
    md5: '997b46093565825309c960cbe86171c5',
  ),
  AtlasRelease(
    filename: 'cities1000.tsv.gz',
    displayName: 'Cities ≥ 1000 population',
    approxCities: 170987,
    url: '$_atlasBaseUrl/cities1000.tsv.gz',
    sizeBytes: 4329765,
    md5: '3a9a5bb068aab873c20b743b84842aad',
  ),
];
