// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Ninth House Studios LLC

enum TracedFunction {
  sweAzalt,
  sweAzaltRev,
  sweCalcPctr,
  sweCalcUt,
  sweCotrans,
  sweDeltat,
  sweFixstar2Ut,
  sweGauquelinSector,
  sweGetAyanamsaExUt,
  sweGetAyanamsaUt,
  sweGetOrbitalElements,
  sweHeliacalUt,
  sweHeliocrossUt,
  sweHouses,
  sweLatToLmt,
  sweLmtToLat,
  sweLunEclipseHow,
  sweLunEclipseWhen,
  sweLunEclipseWhenLoc,
  sweMooncrossNodeUt,
  sweMooncrossUt,
  sweNodApsUt,
  sweOrbitMaxMinTrueDistance,
  swePhenoUt,
  sweRefrac,
  sweRiseTrans,
  sweRiseTransTrueHor,
  sweSetEphePath,
  sweSetJplFile,
  sweSetSidMode,
  sweSetTopo,
  sweSidtime,
  sweSidtime0,
  sweSolcrossUt,
  sweSolEclipseHow,
  sweSolEclipseWhenGlob,
  sweSolEclipseWhenLoc,
  sweSolEclipseWhere,
  sweTimeEqu,
}
